language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
services:
  - postgresql
addons:
  postgresql: "9.5"
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails60.gemfile
script:
  - bundle exec rspec spec/slonik_migration_spec.rb
  - bundle exec rspec spec/slonik_migration_task_spec.rb
